### ISSUE TITLE
Composite video signal issue

### ISSUE THREAD

**Issue by cpufun** [UzixLS/zx-sizif-xxs#1]
Присутствует проблема с композитным видеосигналом. Не удается добиться устойчивого изображения. Картинка срывается постоянно, на одном экране видно четыре изображения, вместо одного, всё изображение - черно-белое.

**Comment by UzixLS** [comment]
Вообще, как написано в readme - "Work in progress", рановато вы начали паять :) 
В любом случае, по меньшей мере ч/б картинка должна быть нормальная. Смотрели
https://github.com/UzixLS/zx-sizif-xxs/blob/master/pcb/rev.A/ERRATA.txt ?

В планах у меня переделать композитный выход на полноценный 8-бит ЦАП + использовать PAL-кодер из Speccy 2010. Он даёт просто отличное качество картинки.

**Comment by cpufun** [comment]
Спасибо, за ваш ответ. Errata.txt уже делал всё, кроме - "R20, R22, R25 should be ???". Их не трогал совсем. Есть какие-то варианты для них?

Думаю было бы хорошо даже без PAL-кодера, сделать резисторный ЦАП с которого снимать RGB-сигнал и синхронизацию. Сейчас существуют отличнейшие переходники [SCART->HDMI](https://aliexpress.ru/item/4000390369950.html?spm=a2g39.orderlist.0.0.28a74aa6WqvqlZ) и выводить все на LCD-телик.

**Comment by UzixLS** [comment]
По R20, R22, R25 сейчас сложно сказать, я подбирал какие-то номиналы, но уже переделал свою плату под 8-бит ЦАП, так что сказать не могу. Можно их вовсе не впаивать, они отвечают только за цвет.
Я очень хотел сделать RGB-выход, но не нашёл ни одного нормального доступного варианта разъёма, с которым плата бы помещалась в корпус клавиатуры.

**Comment by UzixLS** [comment]
Кстати, я покупал как раз SCART->HDMI такой как по ссылке. У него есть неприятные артефакты цифровой обработки. Особенно хорошо они заметны, например, в игре Pre Zu, если спуститься вниз и попрыгать возле левой стены.

**Comment by cpufun** [comment]
А [такой](https://aliexpress.ru/item/32868971740.html?item_id=32868971740&sku_id=65452874420) разъем для RGB как вам ?

Я тоже только сегодня получил SCART->HDMI, мне понравилось что он прекрасно обрабатывает и композитное видео. А вот RGB на нем пока еще я не успел посмотреть.

**Comment by UzixLS** [comment]
Это разъём для управления RGB-лентами. Для передачи видео он не используется, да и не подойдёт - контактов мало. Самое близкое что я знаю - AV разъём PSP. Но он YPbPr, к тому же я не видел его в продаже.

**Comment by UzixLS** [comment]
Насчёт 4 картинок - генератор нужен на 28МГц. Либо можно в ПЛИС сделать из 50 28, но тогда не получится модифицировать плату для 8бит ЦАПа.

**Comment by cpufun** [comment]
Ах да вы правы, там только 4 пина, которых не хватит. На Али есть разъемы для светодиодных лент и [на 5 пинов](https://aliexpress.ru/item/32720108727.html?sku_id=61177556962&spm=a2g2w.productlist.0.0.21875413abfmE8), но они ужасно смотрятся. 

А я  для своих поделок, использую для передачи RGB-видео  разъемы MicroUSB. Там и пинов достаточно, и в любой корпус они подходят.  Я обязательно делаю маркировку - RGB, чтобы туда зарядку 5V случайно не вставили по ошибке. Для серийного производства это не подходит, а для какого-то частного случая возможно.

**Comment by cpufun** [comment]
Спасибо, замена генератора 50Мгц->28Мгц помогла, теперь наблюдаю классический матрац в цвете через композит. Можно проблему закрывать.  Вероятно образ ПЗУ( ROM-файл) надо куда-то подкинуть.

**Comment by UzixLS** [comment]
[zx_ula.zip](https://github.com/UzixLS/zx-sizif-xxs/files/7416487/zx_ula.zip)
Попробуйте этот jic-файл.
В git я пока не заливаю все прошивки т.к. "Work in progress" :)

**Comment by cpufun** [comment]
С этим jic-файлом намного лучше стало, у меня фирменная заставка 128К. Но обратил внимание, периодически ~~горизонтальные~~ вертикальные пиксели появляются на экране и пропадают. Поскольку статус - "Work in progress", это еще не финальная версия, но результаты уже впечатляют. Спасибо вам огромное.
