### ISSUE TITLE
ZX-sizif-xxs

### ISSUE THREAD

**Issue by digits1** [UzixLS/zx-sizif-xxs#2]
Евгений добрый вечер! Очень понравился ваш  проект. Очень хочу повторить. Возник вопрос такого характера. Можно ли применить процессор Z84C0010FEC вместо Z84C0020FEC? Спасибо, с уважением!

**Comment by UzixLS** [comment]
Я пробовал на плате Zero - работает.

**Comment by SCybore** [comment]
Приветствую, Евгений! Можно ли приобрести готовую плату Zero?

**Comment by UzixLS** [comment]
> Приветствую, Евгений! Можно ли приобрести готовую плату Zero?

Можно, например, тут: https://www.pcbway.com/project/shareproject/Sizif_XXS_Zero_rev_A_83378be5.html
